name: mimicdb-quickstart-dev

x-mimic_source_db_config: &mimic_source_db_config
  SOURCE_DB_HOST: localhost
  SOURCE_DB_USER: postgres_source
  SOURCE_DB_NAME: postgres_source

x-mimic_target_db_config: &mimic_target_db_config
  TARGET_DB_HOST: localhost
  TARGET_DB_USER: postgres_target
  TARGET_DB_NAME: postgres_target

services:
  mimic-postgres:
    container_name: tempy
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_source
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres_source
      <<: [*mimic_source_db_config, *mimic_target_db_config]
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB'" ]
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5